import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  es: {
    'nav.inicio': 'Inicio',
    'nav.nosotros': 'Nosotros',
    'nav.productos': 'Productos',
    'nav.soluciones': 'Soluciones',
    'nav.servicios': 'Servicios',
    'nav.casos': 'Casos de Éxito',
    'nav.faq': 'FAQ',
    'nav.contacto': 'Contacto',
    'nav.recursos': 'Recursos',
    'nav.estructura': 'Estructura',
    'hero.title': '¿Tu operación detecta los problemas cuando ya afectan ventas?',
    'hero.subtitle': 'BTEK: Soluciones tecnológicas inteligentes para el sector retail, hospitalidad y salud.',
    'hero.cta': 'Iniciar Cuestionario',
    'hero.fit_title': 'Eleva la experiencia de tus socios con tecnología inteligente. Tecnología que protege, optimiza y hace crecer tu negocio.',
    'hero.fit_desc': 'Más de 3,500 sitios gestionados en México con monitoreo 24/7, soluciones personalizadas y soporte garantizado en menos de 4 horas.',
    'hero.transform': '¿Cómo transformamos la infraestructura tecnológica?',
    'about.who': '¿Quiénes somos?',
    'about.title': 'Transformamos la tecnología en valor para tu empresa.',
    'about.desc': 'En BTEK, transformamos la tecnología en una ventaja competitiva. Con más de 20 años de experiencia, ofrecemos soluciones personalizadas para empresas que buscan seguridad, escalabilidad y productividad.',
    'about.more': 'DESCUBRE MÁS SOBRE NOSOTROS',
    'about.audit': 'SOLICITA UNA AUDITORÍA GRATUITA',
    'about.success': 'VER CASOS DE ÉXITO',
    'about.alliances': 'Alianzas Estratégicas',
    'products.title': 'Conoce nuestros productos',
    'products.benefits_label': 'Beneficios Clave:',
    'products.pak.name': 'Pak Retail',
    'products.pak.desc': 'En el competitivo mundo del retail, cada decisión cuenta y cada segundo sin supervisión puede representar una pérdida de ventas. Los desafíos comunes incluyen la falta de visibilidad en sucursales, supervisión limitada y pérdidas constantes sin explicación.',
    'products.pak.highlight': 'PAK Retail eleva la supervisión al siguiente nivel. Nuestra plataforma basada en inteligencia artificial analiza millones de registros para mostrarte:',
    'products.pak.list1': 'Quién entra y qué zonas visitan.',
    'products.pak.list2': 'El comportamiento de los clientes.',
    'products.pak.list3': 'Cómo responde tu equipo.',
    'products.pak.benefit1': 'Detección de anomalías en tiempo real.',
    'products.pak.benefit2': 'Identificación de reincidentes.',
    'products.pak.benefit3': 'Supervisión remota y centralizada.',
    'products.pak.footer': 'PAK Retail te permite aumentar ventas, reducir pérdidas y mejorar la eficiencia operativa. Todo bajo un modelo OPEX que evita la descapitalización. PAK Retail no solo vigila, transforma: convierte tus cámaras en una herramienta de rentabilidad.',
    'products.hotel.name': 'Hotel Connect',
    'products.hotel.desc': 'HotelConnect es una solución integral diseñada para la industria hotelera que transforma la infraestructura de red en una herramienta estratégica de negocio. El sistema aborda problemas comunes como la conectividad inestable y la falta de datos en tiempo real.',
    'products.hotel.benefit1': 'WiFi de última generación: Garantiza una conexión fluida tanto en habitaciones como en zonas comunes saturadas.',
    'products.hotel.benefit2': 'Analítica de Datos: Permite identificar comportamientos de los huéspedes, optimizar servicios como limpieza y room service, y lanzar campañas de marketing dirigidas.',
    'products.hotel.benefit3': 'Seguridad y Soporte: Incluye videovigilancia inteligente y soporte técnico especializado disponible 24/7/365 gestionado desde un centro de operaciones de red (NOC).',
    'products.hotel.benefit4': 'Rentabilidad: Funciona bajo un modelo OPEX, impulsando la rentabilidad sin requerir una gran inversión inicial de capital.',
    'products.fit.name': 'Fit360',
    'products.fit.desc': 'Descubre FIT360 de BTEK, la solución tecnológica definitiva para gimnasios que buscan optimizar su operación y maximizar ingresos. Esta herramienta transforma la red WiFi de tu centro en un canal de inteligencia de negocios, ofreciendo WiFi de última generación para tus usuarios y mapas de calor para analizar el comportamiento y flujo de personas en tiempo real.',
    'products.fit.footer': 'Además, FIT360 te permite lanzar campañas de marketing digital segmentadas directamente a los celulares de tus clientes y optimizar horarios basados en datos reales de saturación. Todo esto está respaldado por un centro de operaciones (NOC) 24/7 y soporte técnico certificado para garantizar la continuidad operativa de tu negocio.',
    'products.hospi.name': 'HospiTek',
    'products.hospi.desc': 'HospiTek 360 es la solución integral de BTEK diseñada para garantizar la continuidad operativa y la seguridad clínica en hospitales, clínicas y laboratorios. A través de una infraestructura robusta que integra redes seguras, videovigilancia inteligente con IA y sensores de IoT médico, ofrecemos monitoreo 24/7 desde nuestro NOC con tiempos de respuesta garantizados.',
    'products.hospi.footer': 'Nuestra plataforma no solo optimiza la operación técnica, sino que también mejora la experiencia del paciente y sus familiares, generando confianza y reputación mediante datos clínicos y operativos en tiempo real.',
    'solutions.title': 'Tecnología avanzada, resultados medibles.',
    'solutions.subtitle': 'Desde redes escalables hasta ciberseguridad avanzada, diseñamos soluciones que garantizan la continuidad operativa y el crecimiento sostenible de tu empresa.',
    'solutions.view_more': 'VER MÁS',
    'solutions.why_title': '¿Por qué BTEK?',
    'solutions.why_desc': 'Más de 3,500 proyectos implementados, 24x7x4x365 de soporte y un tiempo de respuesta menor a 4 horas. En BTEK garantizamos excelencia operativa.',
    'solutions.why_cta': 'CONOCER CASOS DE ÉXITO',
    'solutions.stat.projects': 'Proyectos',
    'solutions.stat.support': 'Soporte',
    'solutions.stat.response': 'Respuesta',
    'solutions.stat.excellence': 'Excelencia',
    'solutions.stat.presence': 'Presencia en toda la República Mexicana',
    'solutions.item.redes': 'Redes y servicios',
    'solutions.item.redes_desc': 'Infraestructuras robustas que garantizan conectividad continua.',
    'solutions.item.routing': 'Routing y Switching',
    'solutions.item.routing_desc': 'Redes de alto rendimiento que maximizan la velocidad.',
    'solutions.item.wireless': 'WiFi de última generación',
    'solutions.item.wireless_desc': 'Soluciones inalámbricas empresariales con WiFi de última generación: cobertura, rendimiento y movilidad.',
    'solutions.item.cyber': 'Ciberseguridad',
    'solutions.item.cyber_desc': 'Protección avanzada contra amenazas como ransomware.',
    'solutions.item.iot': 'IoT & IA',
    'solutions.item.iot_desc': 'Integración de tecnologías emergentes para optimizar procesos.',
    'solutions.item.cloud': 'Cloud Computing',
    'solutions.item.cloud_desc': 'Infraestructuras flexibles y seguras que soportan operaciones.',
    'solutions.item.workplace': 'Digital Workplace',
    'solutions.item.workplace_desc': 'Herramientas colaborativas diseñadas para optimizar el trabajo.',
    'solutions.item.telephony': 'Telefonía IP',
    'solutions.item.telephony_desc': 'Comunicación simplificada y efectiva, permitiendo la conexión.',
    'solutions.item.video': 'Videovigilancia',
    'solutions.item.video_desc': 'Sistemas inteligentes de monitoreo y seguridad perimetral.',
    'solutions.item.analytics': 'Data Analytics',
    'solutions.item.analytics_desc': 'Análisis avanzado de datos para la toma de decisiones estratégicas.',
    'casos.title': 'Casos de Éxito',
    'casos.subtitle': 'Historias reales de transformación tecnológica en diversos sectores.',
    'casos.cat.retail': 'Retail',
    'casos.cat.hotel': 'Hotelería',
    'casos.cat.health': 'Sector Salud',
    'casos.cat.factory': 'Fábricas y Empresas',
    'faq.title': 'Preguntas Frecuentes',
    'faq.q1': '¿Qué significa que BTEK sea Cisco Premier Partner?',
    'faq.a1': 'Significa que contamos con certificaciones técnicas avanzadas y un nivel de especialización validado por Cisco para diseñar, implementar y soportar sus soluciones con los más altos estándares de calidad.',
    'faq.q2': '¿Qué beneficios ofrece Cisco en comparación con otras marcas de red?',
    'faq.a2': 'Cisco ofrece una confiabilidad inigualable, seguridad integrada desde el hardware, escalabilidad global y un ecosistema de soporte líder en la industria que garantiza la continuidad del negocio.',
    'faq.q3': '¿Qué tipos de soluciones Cisco implementa BTEK?',
    'faq.a3': 'Implementamos soluciones de Routing & Switching, WiFi de última generación, Ciberseguridad (Firewalls, Umbrella), Colaboración, Meraki y soluciones de SD-WAN.',
    'faq.q4': '¿Qué diferencia a una red Cisco administrada por BTEK?',
    'faq.a4': 'La diferencia radica en nuestro monitoreo proactivo 24/7 desde el NOC, tiempos de respuesta menores a 4 horas y una configuración optimizada basada en mejores prácticas internacionales.',
    'faq.q5': '¿Qué ventajas ofrece Cisco Meraki frente a redes tradicionales?',
    'faq.a5': 'Meraki ofrece una gestión 100% basada en la nube, visibilidad total de la red en un solo panel, despliegue rápido (Zero-Touch Provisioning) y actualizaciones automáticas de seguridad.',
    'faq.q6': '¿Qué es una solución SD-WAN de Cisco y por qué es importante?',
    'faq.a6': 'SD-WAN permite gestionar de forma inteligente el tráfico de red entre sucursales, optimizando el uso de enlaces de internet y garantizando el rendimiento de aplicaciones críticas como voz y video.',
    'faq.q7': '¿Cómo protege Cisco las redes empresariales contra ciberataques?',
    'faq.a7': 'Mediante una arquitectura de seguridad integral que incluye visibilidad de amenazas en tiempo real, protección contra malware avanzado (AMP) y segmentación de red para evitar movimientos laterales.',
    'faq.q8': '¿Cisco ofrece soluciones de colaboración empresarial?',
    'faq.a8': 'Sí, Cisco Webex y sus soluciones de telefonía IP ofrecen una plataforma unificada para reuniones, mensajería y llamadas con la mayor seguridad y calidad de audio/video.',
    'faq.q9': '¿Cómo asegura BTEK la correcta configuración de una red Cisco?',
    'faq.a9': 'Seguimos las arquitecturas de diseño validadas por Cisco (CVD) y realizamos pruebas de estrés y auditorías de seguridad antes de la puesta en marcha definitiva.',
    'faq.q10': '¿Qué tipo de mantenimiento ofrece BTEK para equipos Cisco?',
    'faq.a10': 'Ofrecemos mantenimiento preventivo y correctivo, gestión de garantías (SmartNet), actualizaciones de firmware y soporte técnico presencial o remoto 24/7.',
    'faq.q11': '¿Es posible integrar equipos Cisco con otras marcas existentes?',
    'faq.a11': 'Sí, los equipos Cisco utilizan estándares abiertos que permiten la interoperabilidad con la mayoría de las infraestructuras tecnológicas existentes, facilitando una migración gradual.',
    'faq.q12': '¿Cómo ayuda Cisco a reducir costos operativos?',
    'faq.a12': 'A través de la automatización de tareas de red, la reducción de tiempos de inactividad y una mayor eficiencia energética de sus equipos, lo que impacta directamente en el TCO.',
    'faq.q13': '¿Qué niveles de SLA maneja BTEK con Cisco?',
    'faq.a13': 'Manejamos SLAs de misión crítica con tiempos de respuesta de hasta 4 horas (NBD o 24x7x4) para reemplazo de hardware y soporte técnico especializado.',
    'faq.q14': '¿Qué industrias se benefician más de las soluciones Cisco implementadas por BTEK?',
    'faq.a14': 'Retail, Hotelería, Salud, Educación y Manufactura son los sectores que más aprovechan la robustez y seguridad de Cisco para mantener sus operaciones críticas siempre activas.',
    'faq.q15': '¿Cómo puedo saber si una solución Cisco es la adecuada para mi empresa?',
    'faq.a15': 'Realizamos una auditoría técnica gratuita de tu infraestructura actual para identificar áreas de mejora y diseñar una solución a la medida de tus objetivos de negocio.',
    'contact.title': 'Conecta con nosotros',
    'contact.subtitle': 'Estamos listos para ayudarte a transformar tu tecnología en valor.',
    'contact.call': 'Llámanos',
    'contact.email': 'Email',
    'contact.form.name': 'Nombre*',
    'contact.form.position': 'Puesto',
    'contact.form.company': 'Empresa',
    'contact.form.website': 'Sitio Web de la Empresa',
    'contact.form.email': 'Correo*',
    'contact.form.phone': 'Teléfono o WhatsApp',
    'contact.form.location': 'Ubicación',
    'contact.form.solution': 'Solución de interés',
    'contact.form.select': 'Selecciona una opción',
    'contact.form.quote': '¿Qué te interesa cotizar?',
    'contact.form.message': 'Mensaje',
    'contact.form.send': 'Enviar Mensaje',
    'resources.title': 'Recursos y Tecnologías',
    'resources.subtitle': 'Trabajamos con los líderes mundiales en infraestructura tecnológica.',
    'footer.copyright': 'Copyright © 2026. Btek | Todos los derechos reservados.',
    'footer.privacy_link': 'Aviso de Privacidad',
    'privacy.document_title': 'Aviso de Privacidad',
    'privacy.back_home': 'Volver al inicio',
    'privacy.updated': 'Última actualización: abril de 2026',
    'contact.form.privacy_prefix': 'He leído y acepto el',
    'lang.label': 'ES',
    'lang.tooltip': 'Cambiar idioma',
    'org.title': 'Nuestra Estructura Organizacional',
    'org.body': 'La organización de BTEK se articula bajo la Dirección General, que coordina las áreas de Administración e Ingeniería. La Ingeniería concentra las funciones de Operaciones —incluido el NOC (centro de operaciones de red)— y los Servicios Profesionales y Servicios Nivel 3, en línea con la estrategia técnica y el servicio al cliente.',
    'org.dg': 'Dirección General',
    'org.admin': 'Administración',
    'org.ing': 'Ingeniería',
    'org.ops': 'Operaciones',
    'org.sp': 'Servicios Profesionales y Servicios Nivel 3',
    'org.noc': 'NOC',
    'about.map_title': 'Nuestra Presencia en México',
    'about.map_desc': 'Tenemos presencia en toda la República Mexicana, con operación y cobertura en los principales centros económicos para garantizar tiempos de respuesta inmediatos.',
    'map.cdmx': 'Ciudad de México',
    'map.guadalajara': 'Guadalajara',
    'map.monterrey': 'Monterrey',
    'map.riviera': 'Riviera Maya',
  },
  en: {
    'nav.inicio': 'Home',
    'nav.nosotros': 'About Us',
    'nav.productos': 'Products',
    'nav.soluciones': 'Solutions',
    'nav.servicios': 'Services',
    'nav.casos': 'Success Stories',
    'nav.faq': 'FAQ',
    'nav.contacto': 'Contact',
    'nav.recursos': 'Resources',
    'nav.estructura': 'Structure',
    'hero.title': 'Does your operation detect problems only when they affect sales?',
    'hero.subtitle': 'BTEK: Intelligent technological solutions for retail, hospitality, and healthcare sectors.',
    'hero.cta': 'Start Questionnaire',
    'hero.fit_title': 'Elevate your partners\' experience with intelligent technology. Technology that protects, optimizes, and grows your business.',
    'hero.fit_desc': 'More than 3,500 sites managed in Mexico with 24/7 monitoring, personalized solutions, and guaranteed support in less than 4 hours.',
    'hero.transform': 'How do we transform technological infrastructure?',
    'about.who': 'Who are we?',
    'about.title': 'We transform technology into value for your company.',
    'about.desc': 'At BTEK, we transform technology into a competitive advantage. With over 20 years of experience, we offer personalized solutions for companies seeking security, scalability, and productivity.',
    'about.more': 'DISCOVER MORE ABOUT US',
    'about.audit': 'REQUEST A FREE AUDIT',
    'about.success': 'VIEW SUCCESS STORIES',
    'about.alliances': 'Strategic Alliances',
    'products.title': 'Meet our products',
    'products.benefits_label': 'Key Benefits:',
    'products.pak.name': 'Pak Retail',
    'products.pak.desc': 'In the competitive world of retail, every decision counts and every second without supervision can represent a loss of sales. Common challenges include lack of visibility in branches, limited supervision, and constant losses without explanation.',
    'products.pak.highlight': 'PAK Retail takes supervision to the next level. Our AI-based platform analyzes millions of records to show you:',
    'products.pak.list1': 'Who enters and which zones they visit.',
    'products.pak.list2': 'Customer behavior.',
    'products.pak.list3': 'How your team responds.',
    'products.pak.benefit1': 'Real-time anomaly detection.',
    'products.pak.benefit2': 'Identification of repeat offenders.',
    'products.pak.benefit3': 'Remote and centralized supervision.',
    'products.pak.footer': 'PAK Retail allows you to increase sales, reduce losses, and improve operational efficiency. All under an OPEX model that avoids decapitalization. PAK Retail doesn\'t just watch, it transforms: it turns your cameras into a profitability tool.',
    'products.hotel.name': 'Hotel Connect',
    'products.hotel.desc': 'HotelConnect is an integral solution designed for the hospitality industry that transforms network infrastructure into a strategic business tool. The system addresses common problems such as unstable connectivity and lack of real-time data.',
    'products.hotel.benefit1': 'Latest-generation WiFi: Guarantees a smooth connection in both rooms and saturated common areas.',
    'products.hotel.benefit2': 'Data Analytics: Allows identifying guest behaviors, optimizing services like cleaning and room service, and launching targeted marketing campaigns.',
    'products.hotel.benefit3': 'Security and Support: Includes intelligent video surveillance and specialized technical support available 24/7/365 managed from a network operations center (NOC).',
    'products.hotel.benefit4': 'Profitability: Operates under an OPEX model, driving profitability without requiring a large initial capital investment.',
    'products.fit.name': 'Fit360',
    'products.fit.desc': 'Discover FIT360 by BTEK, the ultimate technological solution for gyms looking to optimize their operation and maximize revenue. This tool transforms your center\'s WiFi network into a business intelligence channel, offering latest-generation WiFi for your users and heat maps to analyze behavior and people flow in real time.',
    'products.fit.footer': 'Additionally, FIT360 allows you to launch segmented digital marketing campaigns directly to your customers\' cell phones and optimize schedules based on real saturation data. All this is backed by a 24/7 operations center (NOC) and certified technical support to guarantee your business\'s operational continuity.',
    'products.hospi.name': 'HospiTek',
    'products.hospi.desc': 'HospiTek 360 is the integral solution from BTEK designed to guarantee operational continuity and clinical safety in hospitals, clinics, and laboratories. Through a robust infrastructure that integrates secure networks, intelligent AI video surveillance, and medical IoT sensors, we offer 24/7 monitoring from our NOC with guaranteed response times.',
    'products.hospi.footer': 'Our platform not only optimizes technical operation but also improves the patient and family experience, generating trust and reputation through real-time clinical and operational data.',
    'solutions.title': 'Advanced technology, measurable results.',
    'solutions.subtitle': 'From scalable networks to advanced cybersecurity, we design solutions that guarantee operational continuity and sustainable growth for your company.',
    'solutions.view_more': 'VIEW MORE',
    'solutions.why_title': 'Why BTEK?',
    'solutions.why_desc': 'More than 3,500 projects implemented, 24x7x4x365 support, and a response time of less than 4 hours. At BTEK, we guarantee operational excellence.',
    'solutions.why_cta': 'VIEW SUCCESS STORIES',
    'solutions.stat.projects': 'Projects',
    'solutions.stat.support': 'Support',
    'solutions.stat.response': 'Response',
    'solutions.stat.excellence': 'Excellence',
    'solutions.stat.presence': 'Nationwide presence',
    'solutions.item.redes': 'Networks and services',
    'solutions.item.redes_desc': 'Robust infrastructures that guarantee continuous connectivity.',
    'solutions.item.routing': 'Routing and Switching',
    'solutions.item.routing_desc': 'High-performance networks that maximize speed.',
    'solutions.item.wireless': 'Latest-generation WiFi',
    'solutions.item.wireless_desc': 'Enterprise wireless solutions with latest-generation WiFi: coverage, performance, and mobility.',
    'solutions.item.cyber': 'Cybersecurity',
    'solutions.item.cyber_desc': 'Advanced protection against threats like ransomware.',
    'solutions.item.iot': 'IoT & AI',
    'solutions.item.iot_desc': 'Integration of emerging technologies to optimize processes.',
    'solutions.item.cloud': 'Cloud Computing',
    'solutions.item.cloud_desc': 'Flexible and secure infrastructures that support operations.',
    'solutions.item.workplace': 'Digital Workplace',
    'solutions.item.workplace_desc': 'Collaborative tools designed to optimize work.',
    'solutions.item.telephony': 'IP Telephony',
    'solutions.item.telephony_desc': 'Simplified and effective communication, allowing connection.',
    'solutions.item.video': 'Video Surveillance',
    'solutions.item.video_desc': 'Intelligent monitoring and perimeter security systems.',
    'solutions.item.analytics': 'Data Analytics',
    'solutions.item.analytics_desc': 'Advanced data analysis for strategic decision-making.',
    'casos.title': 'Success Stories',
    'casos.subtitle': 'Real stories of technological transformation in various sectors.',
    'casos.cat.retail': 'Retail',
    'casos.cat.hotel': 'Hospitality',
    'casos.cat.health': 'Healthcare',
    'casos.cat.factory': 'Factories and Companies',
    'faq.title': 'Frequently Asked Questions',
    'faq.q1': 'What does it mean that BTEK is a Cisco Premier Partner?',
    'faq.a1': 'It means we have advanced technical certifications and a specialization level validated by Cisco to design, implement, and support their solutions with the highest quality standards.',
    'faq.q2': 'What benefits does Cisco offer compared to other network brands?',
    'faq.a2': 'Cisco offers unmatched reliability, hardware-integrated security, global scalability, and an industry-leading support ecosystem that ensures business continuity.',
    'faq.q3': 'What types of Cisco solutions does BTEK implement?',
    'faq.a3': 'We implement Routing & Switching, latest-generation WiFi, Cybersecurity (Firewalls, Umbrella), Collaboration, Meraki, and SD-WAN solutions.',
    'faq.q4': 'What differentiates a Cisco network managed by BTEK?',
    'faq.a4': 'The difference lies in our proactive 24/7 monitoring from the NOC, response times of less than 4 hours, and optimized configuration based on international best practices.',
    'faq.q5': 'What advantages does Cisco Meraki offer over traditional networks?',
    'faq.a5': 'Meraki offers 100% cloud-based management, total network visibility in a single dashboard, fast deployment (Zero-Touch Provisioning), and automatic security updates.',
    'faq.q6': 'What is a Cisco SD-WAN solution and why is it important?',
    'faq.a6': 'SD-WAN allows intelligent management of network traffic between branches, optimizing the use of internet links and guaranteeing the performance of critical applications such as voice and video.',
    'faq.q7': 'How does Cisco protect business networks against cyberattacks?',
    'faq.a7': 'Through a comprehensive security architecture that includes real-time threat visibility, advanced malware protection (AMP), and network segmentation to prevent lateral movement.',
    'faq.q8': 'Does Cisco offer business collaboration solutions?',
    'faq.a8': 'Yes, Cisco Webex and its IP telephony solutions offer a unified platform for meetings, messaging, and calls with the highest security and audio/video quality.',
    'faq.q9': 'How does BTEK ensure the correct configuration of a Cisco network?',
    'faq.a9': 'We follow Cisco Validated Designs (CVD) and perform stress testing and security audits before final deployment.',
    'faq.q10': 'What type of maintenance does BTEK offer for Cisco equipment?',
    'faq.a10': 'We offer preventive and corrective maintenance, warranty management (SmartNet), firmware updates, and 24/7 on-site or remote technical support.',
    'faq.q11': 'Is it possible to integrate Cisco equipment with other existing brands?',
    'faq.a11': 'Yes, Cisco equipment uses open standards that allow interoperability with most existing technological infrastructures, facilitating a gradual migration.',
    'faq.q12': 'How does Cisco help reduce operating costs?',
    'faq.a12': 'Through automation of network tasks, reduction of downtime, and greater energy efficiency of its equipment, which directly impacts TCO.',
    'faq.q13': 'What SLA levels does BTEK handle with Cisco?',
    'faq.a13': 'We handle mission-critical SLAs with response times of up to 4 hours (NBD or 24x7x4) for hardware replacement and specialized technical support.',
    'faq.q14': 'Which industries benefit most from Cisco solutions implemented by BTEK?',
    'faq.a14': 'Retail, Hospitality, Healthcare, Education, and Manufacturing are the sectors that most leverage Cisco\'s robustness and security to keep their critical operations always active.',
    'faq.q15': 'How can I know if a Cisco solution is right for my company?',
    'faq.a15': 'We perform a free technical audit of your current infrastructure to identify areas for improvement and design a solution tailored to your business objectives.',
    'contact.title': 'Connect with us',
    'contact.subtitle': 'We are ready to help you transform your technology into value.',
    'contact.call': 'Call us',
    'contact.email': 'Email',
    'contact.form.name': 'Name*',
    'contact.form.position': 'Position',
    'contact.form.company': 'Company',
    'contact.form.website': 'Company Website',
    'contact.form.email': 'Email*',
    'contact.form.phone': 'Phone or WhatsApp',
    'contact.form.location': 'Location',
    'contact.form.solution': 'Solution of interest',
    'contact.form.select': 'Select an option',
    'contact.form.quote': 'What are you interested in quoting?',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send Message',
    'resources.title': 'Resources and Technologies',
    'resources.subtitle': 'We work with world leaders in technological infrastructure.',
    'footer.copyright': 'Copyright © 2026. Btek | All rights reserved.',
    'footer.privacy_link': 'Privacy Notice',
    'privacy.document_title': 'Privacy Notice',
    'privacy.back_home': 'Back to the home page',
    'privacy.updated': 'Last updated: April 2026',
    'contact.form.privacy_prefix': 'I have read and accept the',
    'lang.label': 'EN',
    'lang.tooltip': 'Change language',
    'org.title': 'Our Organizational Structure',
    'org.body': 'BTEK\'s organization is led by General Management, which coordinates Administration and Engineering. Engineering brings together Operations—including the NOC (network operations center)—and Professional Services and Level 3 Services, in line with technical strategy and customer service.',
    'org.dg': 'General Management',
    'org.admin': 'Administration',
    'org.ing': 'Engineering',
    'org.ops': 'Operations',
    'org.sp': 'Professional Services and Level 3 Services',
    'org.noc': 'NOC',
    'about.map_title': 'Our Presence in Mexico',
    'about.map_desc': 'We have nationwide coverage in Mexico, with operations in the main economic centers to guarantee immediate response times.',
    'map.cdmx': 'Mexico City',
    'map.guadalajara': 'Guadalajara',
    'map.monterrey': 'Monterrey',
    'map.riviera': 'Riviera Maya',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['es']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
